work = [
    "You work in the mines for {amount}.",
    "You cut down a tree for {amount}.",
    "You drive women to the store for {amount}.",
    "You work as a software developer and earn {amount}",
    "You work as a behaviour consultant and earn {amount}",
    "You are paid {amount} to clean up hair off the ground at your local hairdressers.",
    "You work as a Red-DiscordBot developer and earn {amount}.",
    "You work for a private military company, earning {amount}",
    "You work as a courier for the day. You are paid {amount}",
    "You did a 30 minute workout. While jogging you found {amount} on the floor.",
    "You shine people's shoes in class and they give you {amount}.",
    "You shine people's shoes in the mall and earn {amount}.",
    "You worked at the office overtime for {amount}.",
    "You worked at the office and earned {amount}.",
    "{amount} falls out of the sky and hits you on the head.",
    "You help a newcomer set up a camp and they pay you {amount}",
    "You work at a summer camp and earn {amount}.",
    "You work in a local bookmakers and earn {amount}.",
    "You work in your local shop and get paid {amount}.",
    "You earn {amount} from a football bet.",
    "You got featured and won {amount}",
    "You work as a vibration consultant and earn {amount}",
    "You worked as a Bride Kidnapping Expert, for that you were paid {amount}",
    "You become a game developer and raised {amount} for charity.",
    "You toasted some bread. A step in the right direction. You earned {amount}",
    "You come home full of sweat after a hard day of boxing, the sponsors give you  {amount}",
    "You put on a spring lock suit and entertain the customers. You receive {amount}",
    "You worked as a diaper changer, you were paid {amount}",
    "You eat bananas for a living and get {amount}",
    "You didn't go to work, but you got your paycheck of {amount} anyway.",
    "You work as a bread scientist and earn {amount}",
    "Nothing says a good day like being a programmer  for C#. You earn {amount} despite you keep Googling all your problems.",
    "You work as a snake milker and earn {amount}",
    "You take your cat for a walk and gain {amount}",
    "You host a fine wine tasting event and get {amount}",
    "You help Preda collect porn for Martine and he pays you {amount}",
    "You work as an extra for Avengers 4. You didn’t feel so good, but you got {amount}",
    "You cleaned 200 toilets in the prison. The lazy janitor thanked you and gave you {amount}",
    "You sweep the floor and get paid {amount}",
    "You put your nose to the grindstone and earned {amount}",
    "You worked and gained {amount}",
    "You work as a comedian and earn {amount}",
    "You work as an experienced boner and earn {amount}",
    "Great job! You work as a professional professional and got {amount}",
    "You've worked on a farm cultivating wheat from dawn to dusk. The land lord pays you {amount} for your struggles.",
    "You work as a window cleaner for the Gherkin in London and earn {amount}",
    "You catch fish for a few hours and give them to your boss. They pay you {amount} for a good job.",
    "You enter a website contest and beat Club Penguin, Twitter, and Facebook. Receive {amount}",
    "You work 10 minutes at a local Pizza Hut. You earned {amount}",
    "You take part in a Civil War battle and earn {amount} for your team winning!",
    "Work at the icecream shop of your childhood dreams and earn {amount}",
    "You work extra hard at the office today, but instead of gaining a promotion you earn a donut and {amount} Good job.",
    "You work as an elephant dresser and earn {amount}",
    "You sold 3 copies of the Shrek movie and earned {amount}",
    "You work as a director of sandbags and earn {amount}",
    "You worked for {amount}",
    "You press some buttons on a keyboard, gaining {amount}",
    "You work as a gender equality consultant and earn {amount}",
    "You did absolutely nothing and still managed to get paid {amount}",
    "You start up a very small company that made near no money before you sold it for {amount}",
    "You create and launch a game on Roblox, it becomes a hit! You get money from people buying early access, in game passes and currency in game, you convert the Robux you earn into server money you got {amount}",
    "You work as a professional sleeper and earn {amount}",
    "You work as a janitor and earn {amount}",
    "You try to find out how many licks it takes to get to the center of a Tootsie Pop. Turns out it's 3 and a crunch. The research team pays you {amount}",
    "You dig around in your yard and gain {amount}",
    "You work as a flatulence smell reduction underwear maker and earn {amount}",
    "You make a living selling weed, for {amount} a day",
    "You work as a police officer and earn {amount}",
    "You work at Mario's Plumbing Service for {amount}",
    "You dig around in your yard and gain {amount}",
    "You drive women to the store for {amount}",
    "You begin to code a game you have been thinking about for a while, and your friends give you {amount} to help fund the project!",
    "You work as a parkour specialist and earn {amount}",
    "You work as a ear cleaner and earn {amount}",
    "You work as a flatulence smell reduction underwear maker and earn {amount}",
    "You worked for the Police and earned {amount}",
    "You work at the dump all day. Then you found {amount} from a thrown out wallet.",
    "You work as a beaver expert and earn {amount}",
    "You worked hard at your dish cleaning job but failed. Then you tried fish cleaning! You earned {amount}",
    "You drive women to the store for {amount}",
    "After scrubbing each toilet twice with a toothbrush, your coworker pays you {amount} as it was originally their job",
    "You battled and gained {amount}",
    "You actually went to work today like a normal person. William throws {amount} at you, ouch!",
    "You clean off the counters and get paid {amount}",
    "You posted something to the subreddit! You've earned {amount}",
    "You work as a PlayStation brand ambassador and earn {amount}",
    "You made a great pun ! Take this : {amount}",
    "You enter a fidget spinner spinning contest and out-spin the other fidget spinner spinners. You make {amount}",
    "You sell your crab for {amount} you monster",
    "Why can't you get a real job and make real money? Because digging through the dirt is more fun. You gain {amount}",
    "You clean off the counters and get paid {amount}",
    "You beat sonic wave infinity and won {amount}",
    "You are kidnapped and taken to an underground coliseum where you fought off monsters with people you’ve never met before. You earn {amount} albeit reluctantly.",
    "You work as a police officer and earn {amount}",
    "You work as a serial murderer... and earn {amount}",
    "You helped the druids to make their potions, they give you {amount}",
    "You overslept and miss work, but a buddy clocked you in so you got paid {amount}",
    "You work as a human statue and earn {amount}",
    "You work as a human scarecrow (yes.. you're that ugly) and earn {amount}",
    "You work for Microsoft's marketing department. You get a free XBOX One S and {amount}",
    "You work as the head of elephants and earn {amount}",
    "You work at Disneyland as a panda in a costume and earn {amount}",
    "You help clean up a local bar, the bar owner pays you {amount} for your work.",
    "You milk cows for a few hours because the farmer is sick! You are paid {amount} for doing their job.",
    "You scavenge a local garbage dump and find {amount} worth of scrap.",
    "You and your mariachi band play music at a wedding. {amount}",
    "You spent an 8 hour shift walking around in 10 inch heels and a nice dress handing out flyers to rude customers. Your feet are killing you, and you can't wait to get that dress off. At least you got paid {amount} for it.",
    "You work as an iceberg mover and earn {amount}",
    "You baked some nice cookies for all, here is {amount}",
    "You help clean up the local theater. You find {amount} strewn about between the seats!",
    "You got cloned for science. You earned {amount}",
    "You work as a voice actor for Spongebob and managed to gain {amount}",
    "You take your dog for a walk and gain {amount}",
    "Taxes collected! You have gained {amount}",
    "You work as a sandwich artist and earn {amount}",
    "You work as a bush pruner for Donald Trump and earn {amount}",
    "You did some social work for a good cause ! You received {amount} for your contributions !",
    "You work as a bounty hunter and earn {amount}",
    "You drive women to the store for {amount}",
    "You dabbed so hard that even your mother is proud! You make {amount} off of donations.",
    "You work as a helpdesk technician and earn {amount}",
    "You work as a plus sized model and earn {amount}",
    "You worked as a businessman and earned {amount}",
    "You defended an old lady from robbers. You got a smooch on the cheek and earned {amount}",
    "You work as a voice actor for Spongebob and managed to gain {amount}",
    "You work as a wine taster and earn {amount}",
    "You get fired for sleeping on the job, but found {amount} on the way back home!",
    "Just take the {amount} and go...",
    "You got out of bed. Have {amount}",
    "You complete a daily quest that takes you about 3 hours and you gain {amount} Even though you lost half of your ammo, broke all of your guns, and your spirit is all but crushed",
    "You work as a personal shopper and earn {amount}",
    "You get a commission request, the payment is {amount}",
    "You found {amount} on the floor.",
    "You work all day at the factory {amount}",
    "After a long day of tolerating your annoying co-workers, your boss pays you extra and you earn {amount}",
    "Your job as a fart collector is very interesting and earns you {amount} .",
    "You see someone struggling to lift a box into their car, you rush over to help them before they hurt themselves. After helping them, they graciously give you {amount}",
    "You work as a streamer and gain {amount} from donations",
    "You work as a smarties expert and earn {amount}",
    "You work from 9 to 5 in a law firm as an accountant, going through profits and expenditure accounts. At the end of the day, the papers earns you {amount}",
    "You work as an elementary school teacher and earn {amount}",
    "You paint a lovely watercolor Moon and sell it at a local art fair for {amount}",
    "You work as a sandcastle builder and earn {amount}",
    "You get a commission request, the payment is {amount}",
    "You work as a body pillow factory salesman on the internet for real weebs, the weebs gave you {amount}",
    "You gave yourself {amount} that you didn't even have! What is this wizardry..",
    "You helped out your boss and worked hard, earning {amount}",
    "You get a letter saying you've won a cash prize of {amount} with an address to collect your winnings at. The weird thing is you don't recall entering any contest...",
    "You work as a fortune cookie writer and earn {amount}",
    "You worked hard at your dish cleaning job but failed. Then you tried fish cleaning! You earned {amount}",
    "You clean off the chairs and get paid {amount}",
    "You scavenge a local garbage dump and find {amount} worth of scrap.",
    "You work as an experienced bra fitter and earn {amount}",
    "You baked some nice cookies for all, here is {amount}",
    "You work hard all day and your boss pays you {amount} after the pizzeria closes down.",
    "You repair the arcade machines and receive {amount}",
    "You work as a body double for Shakira. And your hips really don’t lie. You earn {amount}",
    "You work as an iceberg mover and earn {amount}",
    "You clean poop off the stalls at walmart and get {amount}",
    "You worked hard moving your dad's lawn and he gave you {amount}",
    "You found {amount} on the floor.",
    "You work as a penguinologist and earn {amount}",
    "You pour coffee into a cup and successfully deliver it to a customer for {amount}",
    "You work as a human scarecrow (yes.. you're that ugly) and earn {amount}",
    "You suggest something good and get rewarded {amount}",
    "You work as a taxi driver and earn {amount}",
    "You got more than 1000 subscribers on YouTube, your last video made you really famous, and then come the YouTube money : {amount}",
    "You actually went to work today like a normal person. William throws {amount} at you, ouch!",
    "You work as a cookie cutter and earn {amount}",
    "You work at a lamp store and earn {amount}",
    "You work as a pumpkin painter and are surprised to find {amount} stashed inside one of them.",
    "You work as a highschool student with no life. Have {amount} because we pity you.",
    "You stack cups at 7-11 for 8 hours a day, racking up a measly {amount}",
    "You work as a sandwich artist and earn {amount}",
    "You develop games and earn {amount}",
    "You work as a streamer and gain {amount} from donations",
    "You work as a bed warmer and earn {amount}",
    "You work as a ear cleaner and earn {amount}",
    "You did some odd jobs in the city and earned {amount} Good job !",
    "You receive a check of {amount} after having done some clever business with a friend in the markets.",
    "You work as a part time game programmer. You rake in {amount}",
    "You worked as a substitute teacher in a school and earned {amount} The students loved you !",
    "You work as a dog surfing instructor and earn {amount}",
    "You work as a toy manufacturer and sell toys to kids for {amount}",
    "You work at a chinese camera repair shop and get berated all day and make {amount}",
    "You drove the school bus today and were only 5 minutes late, but you still got {amount} for your efforts!",
    "You got hired as a stripper! You work that pole and make {amount}",
    "You work as a toy manufacturer and sell toys to kids for {amount}",
    "You work as a children's toy tester and earn {amount}",
    "You work as a body pillow factory salesman on the internet for real weebs, the weebs gave you {amount}",
    "You carried a bunch of schoolbags around to different classes for a day, and received {amount} from your peers.",
    "You work as a professional Minecraft hacker. You manage to rake in {amount}",
    "You work as an eel ecologist and earn {amount}",
    "You work as a professional snuggler and earn {amount}",
    "You fixed a broken down T-60 Tank in Afghanistan. The crew paid you {amount} when you got back home",
    "You work as a cross dresser model and earn {amount}",
    "You had a fruitful day at the office today and earned {amount}",
    "You work as a pumpkin picker {amount}",
    "You work at Grandma's restaurant as a cook and earn {amount}",
    "You work as crisis actor and earn {amount}",
    "You work in Subway (other sandwich shops are available) and earn {amount}",
    "You help set up MemeHub, and earned {amount}",
    "You work as a PlayStation brand ambassador and earn {amount}",
    "You got out of bed. Have {amount}",
    "You work as a professional wine taster and earn {amount}",
    "You sell Girl Scout Cookies and earn {amount}",
    "You work as a professional cock fighter and earn {amount}",
    "You work as a professional cleaner. After hiding the body, you're handed {amount}",
    "You serve the customers and receive {amount}",
    "You work as a smarties expert and earn {amount}",
    "You work as a sewer inspector and earn {amount}",
    "Instead of going to work, you decided to look for money on the ground. Fortunately enough, you found {amount}",
    "You have a successful YouTube channel and make {amount} for that sweet, sweet AD revenue",
    "You work in Greggs and earn {amount}",
    "You receive a check of {amount} after having done some clever business with a friend in the markets.",
    "Your work at a market selling apples with a shop clerk for a day. They pay you {amount} for helping them out.",
    "While you were searching for Pokémon in the tall grass, you found {amount}",
    "Just take the {amount} and go...",
    "You and your mariachi band play music at a wedding. {amount}",
    "You are hired by the Mojave Express to deliver a package to The King in Freeside.  You are paid {amount}",
    "You win a spicy chili eating contest. The prize is {amount}",
    "You dabbed so hard that even your mother is proud! You make {amount} off of donations.",
    "Your level got featured epic and you won {amount}",
    "You work as a water slide tester and earn {amount}",
    "You find {amount} randomly lying in the gutter",
    "You do some work around the house for {amount}",
    "The demand for mobile games has increased so you create a new game full of microtransactions. You earn a total of {amount} off your new game.",
    "You beat sonic wave infinity and won {amount}",
    "You work at a lamp store and earn {amount}",
    "While you were searching for Pokémon in the tall grass, you found {amount}",
    "You help clean up the local theater. You find {amount} strewn about between the seats!",
    "You work as a beefeater and earn {amount}",
    "You work as a breath odor evaluator and earn {amount}",
    "You battled and gained {amount}",
    "Mr. Beast came to give you random amounts of money, you received {amount}",
    "You work as an IMAX screen cleaner and earn {amount}",
    "You worked overtime for {amount}",
    "You clean poop off the stalls at Walmart and get {amount}",
    "You work as a space lawyer and earn {amount}",
    "You enter a fidget spinner spinning contest and out-spin the other fidget spinner spinners. You make {amount}",
    "You work as a pumpkin painter and are surprised to find {amount} stashed inside one of them.",
    "You take an hour to patch a broken water pipe in the yard and earn {amount}",
    "You work as a paper towel sniffer and earn {amount}",
    "You helped out your boss and worked hard, earning {amount}",
    "You help clean up a local bar, the bar owner pays you {amount} for your work.",
    "You clean off the animatronics and get paid {amount}",
    "You worked your very best at a printing press which was hiring and earned  your well deserved {amount} !",
    "You work all day at the factory {amount}",
    "Somebody once told me the world was gonna roll me, I ain't the sharpest tool in the sh- oh, uh- you did something good and got {amount} I think...",
    "You work as crisis actor and earn {amount}",
    "You worked for Cubic.Games as their program team member. A measly {amount} was earn.",
    "You work as a professional cuddler and earn {amount}",
    "You sold knock-off Squishees and cashed out with {amount}",
    "You work as an engineer and earn {amount}",
    "You drove new recruits to the base and you got paid {amount} for doing it",
    "You work as a bride kidnapper and earn {amount}",
    "You worked your very best at a printing press which was hiring and earned  your well deserved {amount} !",
    "You carefully clean the spring lock suits and receive {amount}",
    "You work as a professional cat-petter and earn {amount}",
    "You work as a fortune cookie writer and earn {amount}",
    "You hastily wipe down the Café counters. Your boss pays you {amount}",
    "You got cloned for science. You earned {amount}",
    "You clean off the tables and get paid {amount}",
    "You take your dog for a walk and gain {amount}",
    "You work as the namer of clouds and earn {amount}",
    "You take your dog for a walk and gain {amount}",
    "You run a relatively popular Tumblr blog and make {amount} from ad revenue.",
    "You work as a pumpkin picker {amount}",
]
crimes = [
    "You rob a bank for {amount}.",
    "You steal a car and sell it for {amount}.",
    "You steal and car and scrap it for {amount}.",
    "You rob a liquor store for {amount}.",
    "You rob an old woman for {amount}.",
    "You steal a kids bike from the playground for {amount}.",
    "You and your posy rob a bank for {amount}.",
    "You see a man digging up a grave. He pays you {amount} to help him.",
    "You sell drugs on the corner block for {amount}.",
    "You pickpocket a noble and find {amount} in their wallet.",
    "You launder {amount} through a local hairdressers.",
    "You robbed the Grinch and happen to find something in his collection! You sell it for {amount}",
    "You scam an old couple out of {amount}",
    "You earn {amount} from an insurance fraud scheme",
    "You gain {amount} after breaking into a house.",
    "You rob your friends wallet and find {amount}",
    "You find a trading vulnerability in a game and duplicate inventory for which you sell and earn {amount}",
    "You steal your grandma's purse, and find {amount} and some butterscotch candy.",
    "You crack open a safe and shovel {amount} into your pockets. These old people never learn.",
    "You see a man burying a dead body in the park. He pays you {amount} to help him out.",
    "You stole a package from your neighbor and sold it on the deep web for {amount}",
    "You sell your kidney on the black market for {amount}",
    "You steal a painting of a moustached man and sell it for {amount}",
    "You post nudes on the internet for {amount}",
    "You manage to persuade a Lord into thinking that you're a banker. He gives you his {amount} for safe keeping .",
    "You tried to help someone with a bot, but they were greedy and stole {amount} from you!",
    "You sold drugs for {amount}",
    "You rob the Goodsprings General Store and come out with {amount}",
    "You pickpocket a candy seller for {amount}",
    "Your SoundCloud DJ roommate plays their music at 120 DB until 5am in the morning. In a seething blind rage, you kill them and sell their equipment for {amount}",
    "You travel back in time to before the Gold Rush began and take all the gold. You travel back to the present and trade it in for {amount}",
    "Don't tell anybody what you just did. Here is {amount}",
    "You steal a customer's lucky gold coin which you sell for {amount}",
    "On Highway 9 you come across a courier heading to New Tulsa. You have a small conversation and figure out they are transporting a shipment of scavenged poker chips. Filled with greed, you put a bullet in their gut and loot the package. When returning to New Tulsa you sneak the chips into the Hard Rock and cash them in for {amount} No one found out...thank God.",
    "With a few others, you light up a molotov and throw it at a shop. Somehow you find {amount} on the way back.",
    "You steal an apple from the market and saved {amount}",
    "You make a profit selling catnip on the streets, and get {amount}",
    "You went to rob a bank and failed miserably, although you did escape the cops and made it back to your apartment. You found {amount} on the ground in the parking lot.",
    "You successfully created a pyramid scheme making {amount} in the process.",
    "You help illegal immigrants cross the border and they paid you {amount}",
    "You access the point log and clear everything, gaining {amount}",
    "You walk down the street and find someone beating up an old man...so you decided to join in on the fun and get {amount} from the man's wallet.",
    "You pickpocket a man/woman. You manage to get {amount}",
    "You rob a liquor store for {amount}",
    "You stole a couple rifles and sold it for {amount}",
    "You sell your first mixtape and earn {amount}",
    "You start up a detective service for a few days, but when you finally get business you end up robbing your client for {amount}",
    "You hacked this server and got {amount}",
    "You dabbed on the haters and got {amount}",
    "You manage to slip some gemstones into your pockets when the store owner isn't looking, selling them later for {amount}",
    "You kidnap a citizen and take them hostage for {amount}",
    "You successful raid a popular server and steal all their members. You get {amount} in Patron donations.",
    "You download and repost an art tutorial on YouTube that gets a lot of hits, {amount} arrives in the mail the next day.",
    "You robbed a bank and got {amount}",
    "You found {amount} under your bus seat. Shhh! Don't tell anyone.",
    "The Russian government pays you {amount} after you successfully blow up an arms depot.",
    "You steal the Queen's crown and sell it on the black market for {amount}",
    "You kidnap a bride and take her hostage for {amount}",
    "You mug a hobo on the street and manage to get {amount}",
    "You commit a heist and manage to take {amount}",
    "You broke into the Warden's office and stole their chair. You managed to sell it for {amount}",
    "You assassinated an African druglord for {amount}",
    "You rob a McDonald's and take {amount}",
    "On the way to work you decided to rob a store and successfully got {amount}",
    "You travel back in time to before the Gold Rush began and take all the gold. You travel back to the present and trade it in for {amount}",
    "You steal an orange and pawn it for {amount}",
    "You rummage through a dumpster illegally and find {amount}",
    "You steal all the candy from a candy store. After fighting the urge to eat it, you sell it for {amount}",
    "You storm the local police station and steal all their bribery money worth {amount}",
    "You raided the enemy tribe and got {amount}",
    "You steal lamps for {amount}",
    "You sneak into the White House and manage to get your hands on a small loan of a million dollars. Unfortunately, you lose most of it while escaping, and only take home {amount}",
    "The local street gang pays you {amount} after helping them beat an innocent citizen",
    "You steal a car and take it to the junkyard for {amount}",
    "You receive an unmarked letter in the post. Inside is a check of {amount} which probably means that the 'business' went well.",
    "You hacked a bank and stole {amount}",
    "You kill someone and sell their organs for {amount}",
    "You were hired as an assassin and you succeeded, earning {amount}",
    "You rob the bank and obtain {amount} Hell yes.",
    "You see an old woman drop {amount} and take it!",
    "You steal your neighbor's cat and sell it for {amount}",
    "You break into a builder's workshop and manage to steal {amount}",
    "You steal an orange and pawn it for {amount}",
    "You steal a hobo's money jar for {amount}",
    "You did a crime and got {amount} from it :/",
    "You steal a birds egg and sell it on the black market for {amount}",
    "You rob a squirrel of their nuts and pawn them for {amount}",
    "You rob from a bank and gained {amount} for escaping without being caught",
    "You steal a child's piggy bank for {amount}",
    "You stole a potato and sold it for {amount} on the black market",
    "You rob the bank and obtain {amount} Hell yes.",
    "In the guise of darkness you break into a home to steal jewelry worth {amount}",
    "You sell cellular phones for a whopping {amount}",
    "You steal an orange and pawn it for {amount}",
    "You travel back in time to before the Gold Rush began and take all the gold. You travel back to the present and trade it in for {amount}",
    "You stole a fish and sell it second hand for {amount}",
    "You stole a mystery box from Walmart, it was full of turtlenecks valued at {amount}",
    "You're hired as a hitman for {amount}",
    "You hacked into a terrorist's computer, and managed to earn {amount}",
    "You milk your videos with clickbait and giveaway-videos, earning {amount}",
    "The 'Dont Step on the Grass' sign in the park was taunting you, so you pranced all over the grassy fields before picking the pocket of the nearby patrolling traffic officer, you were able to nab {amount} from their pockets.",
    "You robbed a church and made {amount}",
    "You break into a home to steal jewelry worth {amount}",
    "You successfully complete a heist and earn {amount}",
    "You stole a T-55 Tank and sold it for {amount} on the market",
    "You stole a fish and sell it second hand for {amount}",
    "You hack into the government's economy system and manage to steal {amount}",
    "You steal change from the homeless. You got {amount}",
    "Those weren't girl scout cookies, but hey you got {amount}",
    "What me? No, I didn't commit crime. Crime-who? Crime-what? Acquire {amount} for something that definitely wasn't illegal",
    "You murder that sweet old lady living upstairs, collect her jewelry and sell it for {amount}",
    "You rob the bank of Eternity for {amount}",
    "You are paid {amount} to hit yourself.",
    "A box wobbles & falls from a delivery vehicle, landing right infront of you. Inside you find high-quality cigars. These are worth {amount}",
    "You pickpocket a passing noble, guess crime does pay after all. You manage to steal {amount}",
    "You break a window in New York for {amount}",
    "You walk down the street and find someone beating up an old man...so you decided to join in on the fun and get {amount} from the man's wallet.",
    "You are paid {amount} to hit yourself.",
    "You steal candy from some schoolgirls and earn {amount}",
    "The 'Dont Step on the Grass' sign in the park was taunting you, so you pranced all over the grassy fields before picking the pocket of the nearby partroling traffic officer, you were able to nab {amount} from their pockets.",
    "You stole a Mi-24 Helicopter and sold it for {amount} on the market",
    "You hack into the government's economy system and manage to steal {amount}",
    "You start selling steroids to the players on your team. You manage to make {amount}",
    "You break into Discord Headquarters, you steal {amount} and escape unnoticed!",
    "You call a few friends and raid a newspaper shop with machetes. The operation is successful, and from the loot you earn {amount}",
    "You smuggle pugs across the Mexican border for a cool {amount}",
    "You pickpocket every single person in the parliament entrance and sneak away with {amount}",
    "Your hacker friend wires you {amount} Good payroll today gamers.",
    "You held a bus hostage and got paid {amount}",
    "You jump the old lady walking down the street. She had {amount} on her.",
    "You pickpocket someone successfully and steal the money out of their wallet, there was {amount} in it",
    "You rob a convenience store for {amount}",
    "You successful raid a popular server and steal all their members. You get {amount} in Patron donations.",
    "You stole Justin Bieber's wallet and found {amount} in it.",
    "You successfully take furniture from the Furniture Store and sell it online for {amount}",
    "You blow up Bungie Headquarters and earn {amount}",
    "You help an old lady cross the road, {amount} falls out of her purse and you take it!",
    "You kidnaped a cat and took it hostage for {amount}",
    "Your hacker friend wires you {amount} Good payroll today gamers.",
    "A woman gave you {amount} for killing her husband!",
    "You murdered your old CEO and found {amount} in their jacket!",
    "You killed a man, and liked it, you got {amount}",
    "You find {amount} laying on the street",
    "You sell body parts on the black market {amount} in profit.",
    "Your friend said that you couldn't steal the Mona Lisa, so to prove them wrong you stole the Mona Lisa and sold it for {amount}",
    "You break into a hospital and steal all their morphine. You manage to sell all of it on the black market for {amount}",
    "You rob a gas station of all its fidget spinners. You sell them for {amount} to some 11 year olds.",
    "You pickpocket somebody and manage to get {amount}",
    "You sell some cocaine and earn {amount}",
    "You sold drugs for {amount}",
    "You manage to hack into a bank's system and steal {amount}",
    "You break into Discord Headquaters, you steal {amount} and escape unnoticed!",
    "You successfully take furniture from the Furniture Store and sell it online for {amount}",
    "You're hired as a hitman for {amount}",
    "You break into a firework factory and steals all the firecrackers and sell them for {amount}",
    "You find some farming tools and steal a few when people aren't looking and sell them to a farmer for {amount}",
    "What me? No, I didn't commit crime. Crime-who? Crime-what? Acquire {amount} for something that definitely wasn't illegal",
    "A drone drops off your mysterious package and you sell it for {amount}",
    "You hacked your parents' bank account and made {amount}",
    "You've been asked to steal the last tiramisu from the kitchen, you got {amount} for a job well done.",
    "You bombed Antarctica and received {amount}",
    "You rob a liquor store for {amount}",
    "You murder the nice lady next door and sell her dead corpse for {amount}",
    "You break into a builder's workshop and manage to steal {amount}",
    "You steal {amount} from a loan shark, and move to the other side of the world.",
    "You work for a mexican cartel and make {amount}",
    "You set up a fake kickstarter for a game and end up stealing {amount} from unsuspecting investors.",
    "You steal a police car and sell it on the black market for {amount}",
    "You steal the Queen's crown and sell it on the black market for {amount}",
    "You sell cellular phones for a whopping {amount}",
    "You did a crime and got {amount} from it :/",
    "You steal {amount} from your boss and don't get caught.",
    "You hacked Google and stole {amount}",
    "You successful raid a popular server and steal all their members. You get {amount} in Patron donations.",
    "You robbed a church and made {amount}",
    "The Russian government pays you {amount} after you successfully blow up an arms depot.",
    "You set up a fake kickstarter for a game and end up stealing {amount} from unsuspecting investors.",
    "You assassinate an actor for {amount}",
    "You stole a car and sold it for {amount}",
    "With a few others, you light up a molotov and throw it at a shop. Somehow you find {amount} on the way back.",
    "You rob another server for {amount}",
    "You steal a cellphone and sell it on ebay for {amount}",
    "A drone drops off your mysterious package and you sell it for {amount}",
    "You entered the Royal Palace and stole a precious diamond. You then sold it for {amount}",
    "You rob a nearby corner store for {amount}",
    "You blow up Bungie Headquarters and earn {amount}",
    "You stole a dog and sold it to the old lady next door for {amount}",
    "You decided to embrace your inner dark side, and promptly massacre an entire nation, netting you {amount}",
    "You steal your baby sister's allowance money from her sparkly pink piggy bank. {amount}",
    "You sell body parts on the black market {amount} in profit.",
    "You were going to commit a crime but changed your mind and got a job instead. You made {amount} before your boss realized you were a criminal and fired you.",
    "You steal someone's Halloween candy, and give your friend half of it. They pay you {amount}",
    "You rob a gas station of all its fidget spinners. You sell them for {amount} to some 11 year olds.",
    "You walk down the street and find someone beating up an old man...so you decided to join in on the fun and get {amount} from the man's wallet.",
    "You sell body parts on the black market {amount} in profit.",
    "You pickpocket someone successfully and steal the money out of their wallet, there was {amount} in it",
    "You did a crime and for some reason you now have {amount} more",
    "You hack into the Red-DiscordBot patreon and rob {amount}.",
    "You steal an apple from the market worth {amount}",
    "You hacked into a terrorist's computer and managed to earn {amount}",
    "You rob a wild bank and manage to steal {amount}",
    "You rob another server for {amount}",
    "You robbed {amount} from a convenience store.",
    "You find some farming tools and steal a few when people aren't looking and sell them to a farmer for {amount}",
    "You rob an orphanage for {amount}",
    "You stealthily pickpocket a nearby customer with {amount} worth of silver coins.",
    "You hacked into the bank and received {amount} and an invitation to Anonymous",
    "You steal your grandma's purse, and find {amount} and some butterscotch candy.",
    "You work for the Juarez cartel as a brick-presser and earn {amount} They'll probably kill you and your family tomorrow. Just saying.",
    "You steal a pink McLaren and sell it to Kim Kardashian for {amount}",
    "You steal a painting of a mustached man and sell it for {amount}",
    "A drone drops off your mysterious package and you sell it for {amount}",
    "You robbed a bank and secured {amount}",
    "You mug someone in a video game for all that they have, too bad it wasn't anything but some worthless bottle caps, netting you {amount}",
    "Walking along the street, you notice an envelope falling out of the person's bag in front of you. You reach down to get it. After examining the unmarked envelope in your hand, you turn to the person who dropped it, they see you with it and run away at full-speed shoving everyone out of the way. Inside you find a small bag of cocaine. You turn to the nearest junkie & show them the contents, the junkie puts {amount} in your hand silently in exchange for it and walks away.",
    "You stole from the cookie jar and gave them to your friend for {amount}",
    "You storm the local police station and steal all their bribery money worth {amount}",
    "You download and repost an art tutorial on YouTube that gets a lot of hits, {amount} arrives in the mail the next day.",
    "You decided to embrace your inner dark side, and promptly massacre an entire nation, netting you {amount}",
    "You work for the Juarez cartel as a brick-presser and earn {amount} They'll probably kill you and your family tomorrow. Just saying.",
    "You sell some cocaine and earn {amount}",
    "You need some extra cash for your drug habit. You break into the local dirty video store and rob them of {amount} You also take a few “items” for yourself...",
    "You steal a painting of a mustached man and sell it for {amount}",
    "You steal a birds egg and sell it on the black market for {amount}",
    "You hack into the mainframe, getting {amount} in the process",
    "You commit a heist and manage to take {amount}",
    "You rob a convenience store for {amount}",
    "You assassinate an actor for {amount}",
    "You hacked into the bank and received {amount} and an invitation to Anonymous",
    "You steal {amount} from a child and (narrowly) escape.",
    "You successfully posted ads in the Red server without Aikaterna catching you, you've earned {amount}.",
    "You start selling steroids to the players on your team. You manage to make {amount}",
    "You stole a prized diamond from the nearby bank vault, selling it for {amount}",
    "You break into a builder's workshop and manage to steal {amount}",
    "You robbed {amount} from a convenience store.",
    "You stole a car and sold it for {amount}",
    "You hacked a bank and stole {amount}",
    "You steal {amount} from a loan shark, and move to the other side of the world.",
    "You robbed {amount} from a convenience store.",
    "You find a wallet on the ground containing {amount} You pick it up and look at the ID inside. You see the man on the ID card running around frantically looking for said wallet. You pocket the wallet and walk away.",
    "You got a cop drunk and stole their car, selling the parts for {amount}",
    "You hacked this server and got {amount}",
    "You do a heist on the EU bank for {amount}",
    "You are paid {amount} to hit yourself.",
    "You ransacked your manager's home, found their prized alarm clock, and sold it for {amount}",
    "You managed to steal an iPhone X and sold it for {amount}",
    "You robbed a random slut you found on street for {amount} You also got a free service",
    "You rob a wild bank and manage to steal {amount}",
    "You rob a gas station of all its fidget spinners. You sell them for {amount} to some 11 year olds.",
    "You robbed a Kwik-E Mart and cashed out with {amount}",
    "You hacked into the bank and received {amount} and an invitation to Anonymous",
    "You stole Justin Bieber's wallet and found {amount} in it.",
    "A box wobbles & falls from a delivery vehicle, landing right in front of you. Inside you find high-quality cigars. These are worth {amount}",
    "You start up a detective service for a few days, but when you finally get business you end up robbing your client for {amount}",
    "You were a hacker and stole robux {amount}",
    "As you exit your backyard, a dog from down the street bites your leg leaving you with deep cuts on your calf. You stumble with pain and kick the dog into your backyard before closing the gate. Later that day a Lost Dog poster is seen on the street offering a reward. You return the dog, only after receiving your {amount} reward. They shouldn't have bit you on your own property.",
    "You were going to commit a crime but changed your mind and got a job instead. You made {amount} before your boss realized you were a criminal and fired you.",
    "You raided the enemy tribe and got {amount}",
    "You set fire to Starbucks and steal all the coffee worth {amount}",
    "You sold drugs for {amount}",
    "You rob the bank of Eternity for {amount}",
    "You steal {amount} from your boss and don't get caught.",
]
