work = [
    "You work in the mines for {amount}.",
    "You cut down a tree for {amount}.",
    "You drive women to the store for {amount}.",
    "You work as a software developer and earn {amount}",
    "You work as a behaviour consultant and earn {amount}",
    "You are paid {amount} to clean up hair off the ground at your local hairdressers.",
    "You work as an Red-DiscordBot developer and earn {amount}.",
    "You work for a private military company, earning {amount}",
    "You work as a courier for the day. You are paid {amount}",
    "You did a 30 minute workout. While jogging you found {amount} on the floor.",
    "You shine people's shoes in class and they give you {amount}.",
    "You shine people's shoes in the mall and earn {amount}.",
    "You worked at the office overtime for {amount}.",
    "You worked at the office and earned {amount}.",
    "{amount} falls out of the sky and hits you on the head.",
    "You help a newcomer set up a camp and he pays you {amount}",
    "You work at a summer camp and earn {amount}."
    "You work in a local bookmakers and earn {amount}.",
    "You work in your local shop and get paid {amount}.",
    "You earn {amount} from a football bet.",
    "You got featured and won {amount}",
    "You work as a vibration consultant and earn {amount}",
    "You worked as a Bride Kidnapping Expert, for that you were paid {amount}",
    "You become a game developer and raised {amount} for charity.",
    "You toasted some bread. A step in the right direction. You earned {amount}",
    "You come home full of sweat after a hard day of boxing, the sponsors give you  {amount}",
    "You put on a spring lock suit and entertain the customers. You receive {amount}",
    "You worked as a diaper changer, you were paid {amount}",
    "You eat bananas for a living and get {amount}",
    "You didn’t go to work, but you got your paycheck of {amount} anyway.",
    "You work as a bread scientist and earn {amount}",
    "Nothing says a good day like being a programmer  for C#. You earn {amount} despite you keep Googling all your problems.",
    "You work as a snake milker and earn {amount}",
    "You take your cat for a walk and gain {amount}",
    "You host a fine wine tasting event and get {amount}",
    "You work as an extra for Avengers 4. You didn’t feel so good, but you got {amount}",
    "You cleaned 200 toilets in the prison. The lazy janitor thanked you and gave you {amount}",
    "You sweep the floor and get paid {amount}",
    "You put your nose to the grindstone and earned {amount}",
    "You worked and gained {amount}",
    "You work as a comedian and earn {amount}",
    "You work as an experienced boner and earn {amount}",
    "You put your nose to the grindstone and earned {amount}",
    "Great job! You work as a professional professional and got {amount}",
    "You've worked on a farm cultivating wheat from dawn to dusk. The land lord pays you {amount} for your struggles.",
    "You work as a window cleaner for the Gherkin in London and earn {amount}",
    "{amount} falls out of the sky and hits you on the head.",
    "You catch fish for a few hours and give them to your boss. He pays you {amount} for a good job.",
    "You did a 30 minute workout. While jogging you found {amount} on the floor.",
    "You toasted some bread. A step in the right direction. You earned {amount}",
    "You enter a website contest and beat Club Penguin, Twitter, and Facebook. Receive {amount}",
    "You work 10 minutes at a local Pizza Hut. You earned {amount}",
    "You take part in a Civil War battle and earn {amount} for your team winning!",
    "Work at the icecream shop of your childhood dreams and earn {amount}",
    "You work extra hard at the office today, but instead of gaining a promotion you earn a donut and {amount} Good job.",
    "You worked at the office overtime for {amount}",
    "You work as an elephant dresser and earn {amount}",
    "You sold 3 copies of the Shrek movie and earned {amount}",
    "You work as a director of sand bags and earn {amount}",
    "You worked for {amount}",
    "You press some buttons on a keyboard, gaining {amount}",
    "You work as a gender equality consultant and earn {amount}",
    "You did absolutely nothing and still managed to get paid {amount}",
    "You work as an extra for Avengers 4. You didn’t feel so good, but you got {amount}",
    "You start up a very small company that made near no money before you sold it for {amount}",
    "You take your cat for a walk and gain {amount}",
    "You create and launch a game on Roblox, it becomes a hit! You get money from people buying early access, in game passes and currency in game, you convert the Robux you earn into server money you got {amount}",
    "You worked at the office overtime for {amount}",
    "You work as a window cleaner for the Gherkin in London and earn {amount}",
    "You work as a professional sleeper and earn {amount}",
    "You work as a janitor and earn {amount}",
    "You try to find out how many licks it takes to get to the center of a Tootsie Pop. Turns out it's 3 and a crunch. The research team pays you {amount}",
    "You dig around in your yard and gain {amount}",
    "You work as a flatulence smell reduction underwear maker and earn {amount}",
    "You take part in a Civil War battle and earn {amount} for your team winning!",
    "You work as a bread scientist and earn {amount}",
    "You make a living selling weed, for {amount} a day",
    "You work as a police officer and earn {amount}",
    "Great job! You work as a professional professional and got {amount}",
    "You work at Mario's Plumbing Service for {amount}",
    "You dig around in your yard and gain {amount}",
    "You drive women to the store for {amount}",
    "You begin to code a game you have been thinking about for a while, and your friends give you {amount} to help fund the project!",
    "You work as a parkour specialist and earn {amount}",
    "You work as a ear cleaner and earn {amount}",
    "You work as a flatulence smell reduction underwear maker and earn {amount}",
    "You work extra hard at the office today, but instead of gaining a promotion you earn a donut and {amount} Good job.",
    "You worked for the Police and earned {amount}",
    "You work at the dump all day. Then you found {amount} from a thrown out wallet.",
    "You work as a beaver expert and earn {amount}",
    "You worked hard at your dish cleaning job but failed. Then you tried fish cleaning! You earned {amount}",
    "You drive women to the store for {amount}",
    "After scrubbing each toilet twice with a toothbrush, your coworker pays you {amount} as it was originally their job",
    "You battled and gained {amount}",
    "You work 10 minutes at a local Pizza Hut. You earned {amount}",
    "You actually went to work today like a normal person. William throws {amount} at you, ouch!",
    "You clean off the counters and get paid {amount}",
    "You posted something to the subreddit! You’ve earned {amount}",
    "You work as a PlayStation brand ambassador and earn {amount}",
    "You made a great pun ! Take this : {amount}",
    "You enter a fidget spinner spinning contest and out-spin the other fidget spinner spinners. You make {amount}",
    "You sell your crab for {amount} you monster",
    "You work as an experienced boner and earn {amount}",
    "Why can't you get a real job and make real money? Because digging through the dirt is more fun. You gain {amount}",
    "You clean off the counters and get paid {amount}",
    "You beat sonic wave infinity and won {amount}",
    "You are kidnapped and taken to an underground coliseum where you fought off monsters with people you’ve never met before. You earn {amount} albeit reluctantly.",
    "You work as a police officer and earn {amount}",
    "You work as a serial murderer... and earn {amount}",
    "You helped the druids to make their potions, they give you {amount}",
    "Work at the icecream shop of your childhood dreams and earn {amount}",
    "You got featured and won {amount}",
    "You work as an extra for Avengers 4. You didn’t feel so good, but you got {amount}",
    "You overslept and miss work, but a buddy clocked you in so you got paid {amount}",
    "You eat bananas for a living and get {amount}",
    "You work as a human statue and earn {amount}",
    "You sold 3 copies of the Shrek movie and earned {amount}",
    "You work as a human scarecrow (yes.. you're that ugly) and earn {amount}",
    "You work for Microsoft’s marketing department. You get a free XBOX One S and {amount}",
    "You work as an extra for Avengers 4. You didn’t feel so good, but you got {amount}",
    "You work as the head of elephants and earn {amount}",
    "You work at Disneyland as a panda in a costume and earn {amount}",
    "You help clean up a local bar, the bar owner pays you {amount} for your work.",
    "You milk cows for a few hours because the farmer is sick! You are paid {amount} for doing his job.",
    "You work as a comedian and earn {amount}",
    "You scavenge a local garbage dump and find {amount} worth of scrap.",
    "You and your mariachi band play music at a wedding. {amount}",
    "You spent an 8 hour shift walking around in 10 inch heels and a nice dress handing out flyers to rude customers. Your feet are killing you, and you can't wait to get that dress off. At least you got paid {amount} for it.",
    "You work as an iceberg mover and earn {amount}",
    "You baked some nice cookies for all, here is {amount}",
    "Work at the icecream shop of your childhood dreams and earn {amount}",
    "You help clean up the local theater. You find {amount} strewn about between the seats!",
    "You got cloned for science. You earned {amount}",
    "You work as a voice actor for Spongebob and managed to gain {amount}",
    "You work as a director of sand bags and earn {amount}",
    "You didn’t go to work, but you got your paycheck of {amount} anyway.",
    "You take your dog for a walk and gain {amount}",
    "Taxes collected! You have gained {amount}",
    "You work as a sandwich artist and earn {amount}",
    "You work as a bush pruner for Donald Trump and earn {amount}",
    "You did some social work for a good cause ! You recieved {amount} for your contributions !",
    "You work as a bounty hunter and earn {amount}",
    "You drive women to the store for {amount}",
    "You dabbed so hard that even your mother is proud! You make {amount} off of donations.",
]
crimes = [
    "You rob a bank for {amount}.",
    "You steal a car and sell it for {amount}.",
    "You steal and car and scrap it for {amount}.",
    "You rob a liqor store for {amount}.",
    "You rob an old woman for {amount}.",
    "You steal a kids bike from the playground for {amount}.",
    "You and your posy rob a bank for {amount}.",
    "You see a man digging up a grave. He pays you {amount} to help him.",
    "You sell drugs on the corner block for {amount}.",
    "You pickpocket a noble and find {amount} in his wallet.",
    "You launder {amount} through a local hairdressers.",
    "You robbed the Grinch and happen to find something in his collection! You sell it for {amount}",
    "You scam an old couple out of {amount}",
    "You earn {amount} from an insurance fraud scheme",
    "You gain {amount} after breaking into a house.",
    "You rob your friends wallet and find {amount}",
    "You find a trading vulnerability in a game and duplicate inventory for which you sell and earn {amount}",
    "You steal your grandma’s purse, and find {amount} and some butterscotch candy.",
    "You crack open a safe and shovel {amount} into your pockets. These old people never learn.",
    "You see a man burying a dead body in the park. He pays you {amount} to help him out.",
    "You stole a package from your neighbor and sold it on the deep web for  {amount}",
    "You sell your kidney on the black market for {amount}",
    "You steal a painting of a moustached man and sell it for {amount}",
    "You post nudes on the internet for {amount}",
    "You manage to persuade a Lord into thinking that you're a banker. He gives you his {amount} for safe keeping .",
    "You tried to help someone with a bot, but they were greedy and stole {amount} from you!",
    "You sold drugs for {amount}",
    "You rob the Goodsprings General Store and come out with {amount}",
    "You pickpocket a candy person for {amount}",
    "Your Soundcloud DJ roommate plays his music at 120 DB until 5am in the morning. In a seething blind rage, you kill him and sell his equipment for {amount}",
    "You travel back in time to before the Gold Rush began and take all the gold. You travel back to the present and trade it in for {amount}",
    "You pickpocket a candy person for {amount}",
    "Don't tell anybody what you just did. Here is {amount}",
    "You steal a customer's lucky gold coin which you sell for {amount}",
    "On Highway 9 you come across a courier heading to New Tulsa. You have a small conversation and figure out he is transporting a shipment of scavenged poker chips. Filled with greed you put a bullet in his gut and loot the package. When returning to New Tulsa you sneak the chips into the Hard Rock and cash them in for {amount} No one found out...thank God.",
    "With a few others, you light up a molotov and throw it at a shop. Somehow you find {amount} on the way back.",
    "You steal the apple from the maket {amount}",
    "You make a profit selling catnip on the streets, and get {amount}",
    "You went to rob a bank and failed miserably, although you did escape the cops and made it back to your apartment. You found {amount} on the ground in the parking lot.",
    "You successfully created a pyramid scheme making {amount} in the process.",
    "You help illegal immigrants cross the border and they paid you {amount}",
    "You access the point log and clear everything, gaining {amount}",
    "You walk down the street and find someone beating up an old man...so you decided to join in on the fun and get {amount} from the man's wallet.",
    "You pickpocket a man/woman. You manage to get {amount}",
    "You rob a liquor store for {amount}",
    "You stole a couple rifles and sold it for {amount}",
    "You sell your first mixtape and earn {amount}",
    "You start up a detective service for a few days, but when you finally get business you end up robbing your client for {amount}",
    "You stole a package from your neighbor and sold it on the deep web for  {amount}",
    "You hacked this server and got {amount}",
    "You dabbed on the haters and got {amount}",
    "You manage to slip some gemstones into your pockets when the store owner isn't looking, selling them later for {amount}",
    "You kidnap a citizen and take  them hostage for {amount}",
    "You successful raid a popular server and steal all their members. You get {amount} in Patron donations.",
    "You download and repost an art tutorial on YouTube that gets a lot of hits, {amount} arrives in the mail the next day.",
    "You robbed a bank and got {amount}",
    "You found {amount} under your bus seat. Shhh! Don't tell anyone.",
    "The Russian government pays you {amount} after you successfully blow up an arms depot.",
    "You steal the Queen's crown and sell it on the black market for {amount}",
    "You kidnap a bride and take her hostage for {amount}",
    "You mug a hobo on the street and manage to get {amount}",
    "You commit a heist and manage to take {amount}",
    "You broke into the Warden's office and stole his chair. You managed to sell it for {amount}",
    "You assassinated an African druglord for {amount}",
    "You rob a McDonald's and take {amount}",
    "On the way to work you decided to rob a store and successfully got {amount}",
    "You travel back in time to before the Gold Rush began and take all the gold. You travel back to the present and trade it in for {amount}",
    "You steal an orange and pawn it for {amount}",
    "You rummage through a dumpster illegally and find {amount}",
    "You steal all the candy from a candy store. After fighting the urge to eat it, you sell it for {amount}",
    "You storm the local police station and steal all their bribery money worth {amount}",
    "You raided the enemy tribe and got {amount}",
    "You steal lamps for {amount}",
    "You sneak into the White House and manage to get your hands on a small loan of a million dollars. Unfortunately, you lose most of it while escaping, and only take home {amount}",
    "You kidnap a bride and take her hostage for {amount}",
    "The local street gang pays you {amount} after helping them beat an innocent citizen",
    "You steal a car and take it to the junkyard {amount}",
    "You recieve an unmarked letter in the post. Inside is a check of {amount} which probably means that the 'business' went well.",
    "You hacked a bank and stole {amount}",
    "You kill someone and sell their organs for {amount}",
    "You were hired as an assassin and you succeeded, earning {amount}",
    "You were hired as an assassin and you succeeded, earning {amount}",
    "You steal a car and take it to the junkyard {amount}",
    "You rob the bank and obtain {amount} Hell yes.",
    "You see an old woman drop {amount} and take it!",
    "You steal your neighbours cat and sell it for {amount}",
    "You break into a builder's workshop and manage to steal {amount}",
    "You steal an orange and pawn it for {amount}",
    "You steal a hobo's money jar for {amount}",
    "You did a crime and got {amount} from it :/",
    "You steal a birds egg and sell it on the black market for {amount}",
    "You rob a squirrel of his nuts and pawn them for {amount}",
    "You rob from a bank and gained {amount} for escaping without being caught",
    "You steal a hobo's money jar for {amount}",
    "You steal a childs piggy bank for {amount}",
    "You stole a potato and sold it for {amount} on the black market",
    "You rummage through a dumpster illegally and find {amount}",
    "You make a profit selling catnip on the streets, and get {amount}",
    "You steal a car and take it to the junkyard {amount}",
    "You kidnap a citizen and take  them hostage for {amount}",
    "You rob the bank and obtain {amount} Hell yes.",
    "In the guise of darkness you break into a home to steal jewelry worth {amount}",
    "You see a man burying a dead body in the park. He pays you {amount} to help him out.",
    "You sell cellular phones for a whopping {amount}",
    "You rummage through a dumpster illegally and find {amount}",
    "You steal an orange and pawn it for {amount}",
    "You travel back in time to before the Gold Rush began and take all the gold. You travel back to the present and trade it in for {amount}",
    "You stole a fish and sell it second hand for {amount}",
    "You manage to slip some gemstones into your pockets when the store owner isn't looking, selling them later for {amount}",
    "You stole a mystery box from Walmart, it was full of turtlenecks valued at {amount}",
    "You're hired as a hitman for {amount}",
    "You sell your kidney on the black market for {amount}",
    "You hacked into a terrorist's computer, and managed to earn {amount}",
    "You milk your videos with clickbait and giveaway-videos, earning {amount}",
    "The 'Dont Step on the Grass' sign in the park was taunting you, so you pranced all over the grassy fields before picking the pocket of the nearby partroling traffic officer, you were able to nab {amount} from their pockets.",
    "You steal a customer's lucky gold coin which you sell for {amount}",
    "You robbed a church and made {amount}",
    "You rob a squirrel of his nuts... and pawn them for {amount}",
    "You went to rob a bank and failed miserably, although you did escape the cops and made it back to your apartment. You found {amount} on the ground in the parking lot.",
    "You dabbed on the haters and got {amount}",
    "You successfully created a pyramid scheme making {amount} in the process.",
    "You rob a squirrel of his nuts... and pawn them for {amount}",
    "You crack open a safe and shovel {amount} into your pockets. These old people never learn.",
    "You break into a home to steal jewelry worth {amount}",
    "You successfully complete a heist and earn {amount}",
    "You Stole a T-55 Tank and sold it for {amount} on the market",
    "You rob a squirrel of his nuts and pawn them for {amount}",
    "You see a man burying a dead body in the park. He pays you {amount} to help him out.",
    "You stole a fish and sell it second hand for {amount}",
    "You hack into the government's economy system and manage to steal {amount}",
    "You robbed the Grinch and happen to find something in his collection! You sell it for {amount}",
    "You rob the Goodsprings General Store and come out with {amount}",
    "You steal change from the homeless. You got {amount}",
    "Those weren't girl scout cookies, but hey you got {amount}",
    "What me? No, I didn't commit crime. Crime-who? Crime-what? Acquire {amount} for something that definitely wasn't illegal",
    "You steal all the candy from a candy store. After fighting the urge to eat it, you sell it for {amount}",
    "You murder that sweet old lady living upstairs, collect her jewelry and sell it for {amount}",
    "You rob the bank of Eternity for {amount}",
    "You kidnap a citizen and take  them hostage for {amount}",
    "You are paid {amount} to hit yourself.",
    "You steal a hobo's money jar for {amount}",
    "A box wobbles & falls from a delivery vehicle, landing right infront of you. Inside you find high-quality cigars. These are worth {amount}",
    "You find a trading vulnerability in a game and duplicate inventory for which you sell and earn {amount}",
    "You pickpocket a passing noble, guess crime does pay after all. You manage to steal {amount}",
    "You rob the Goodsprings General Store and come out with {amount}",
    "You crack open a safe and shovel {amount} into your pockets. These old people never learn.",
    "You break a window in New York for {amount}",
    "You walk down the street and find someone beating up an old man...so you decided to join in on the fun and get {amount} from the man's wallet.",
    "You are paid {amount} to hit yourself.",
    "You dabbed on the haters and got {amount}",
    "Those weren't girl scout cookies, but hey you got {amount}",
]
